# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-22 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='bf_channel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='experiment',
            name='gfp_channel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
